name: 🚀 Publish
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 🧪 Test
    strategy:
      matrix:
        version: [14, 16, 18, 20]
        include:
          - version: 20
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Type checking
        run: pnpm run type-check

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

  publish:
    name: ⚙️ Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: ⚙️ Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
